### ISSUE TITLE
Archives and Popular Tags not shown on item-pages

### ISSUE THREAD

**Issue by McGlear** [hibbitts-design/grav-theme-quark-open-publishing#12]
While "Archive" entries and "Popular Tags" get rendered on the listings page (like the home of this theme's  [demo](http://demo.hibbittsdesign.org/grav-open-publishing-quark/)), they do not appear on the actual blog [item](http://demo.hibbittsdesign.org/grav-open-publishing-quark/blog/hero-classes) pages. 
Only the respective headers are put into the sidebar.

![noarchives](https://user-images.githubusercontent.com/8162769/50773109-2234ff80-1290-11e9-961f-4e284e274e1a.PNG)

____

The base Quark theme doesn't have this problem (compare the single item page behaviour in the [blog-skeleton demo](https://demo.getgrav.org/blog-skeleton/blog/random-thoughts)) and outputs the tags and archive entries as expected.

**Comment by paulhibbitts** [comment]
Hi @McGlear , thanks for reporting this issue.

Re: Archives display, this was due to mistakenly including the needed setting to support multiple blogs in the Open Publishing skeleton. Here is the YAML for the Archives plugin to get that working:

```
enabled: true
built_in_css: true
date_display_format: 'F Y'
show_count: true
limit: 12
order:
  by: date
  dir: desc
filter_combinator: and
filters:
    category: blog
taxonomy_names:
  month: archives_month
  year: archives_year
```

I've identified the issue with Popular Tags and will be releasing a theme update shortly to address that issue.

Please let me know how things go once that update is released.
Paul
